tcpobjs = ARP.OBJ ETH.OBJ ETHTYPE.OBJ IPASM.OBJ IP.OBJ IPTYPE.OBJ PACKET.OBJ TCP.OBJ TCPSOCKM.OBJ TIMER.OBJ TRACE.OBJ UTILS.OBJ
botobjs = bot.obj
testobjs = testio.obj

all : bot.exe test.exe

clean : .symbolic
  @del /q obj\tcplib
  @del /q obj\test
  @del /q obj\bot
  @del /q obj\
  @del *.exe
  @del *.sym
  @del *.map
  @del *.log

.asm : tcplib;test;bot;

.cpp : tcplib;test;bot;

.obj : obj\tcplib;obj\test\;obj\bot;

.asm.obj : 
  wasm -0 -ms $[* -fo=obj\$[*.obj -fr=obj\$[&.err

.cpp.obj :
  wpp $[* -fc=ppargs -fo=obj\$[*.obj -fr=obj\$[&.err

hello.obj : bot\hello.asm
  nasm -f obj bot\hello.asm -o obj\bot\hello.obj

bot.exe: $(tcpobjs) $(botobjs)
  wlink name $@ file obj\tcplib\*.obj,obj\bot\*.obj

test.exe: $(tcpobjs) $(testobjs)
  wlink name $@ file obj\tcplib\*.obj,obj\test\*.obj
