tcp_h_dir = .\TCPINC\
tcp_c_dir = .\TCPLIB\

memory_model = -ms
compile_options = $(memory_model) -wx -0 -zq -DCFG_H="mtcp.cfg" -d1 -os -oa -zmf
compile_options += -i=$(tcp_h_dir)

#tcpobjs = packet.obj arp.obj eth.obj ip.obj tcp.obj tcpsockm.obj udp.obj utils.obj dns.obj timer.obj ipasm.obj
tcpobjs = packet.obj arp.obj eth.obj ip.obj tcp.obj utils.obj tcpsockm.obj timer.obj ipasm.obj
objs = bot.obj hello.obj

all : bot.com

clean : .symbolic
  @del bot.com
  @del trace.txt
  @del *.sym
  @del *.obj
  @del *.err
  @del *.map

.asm : $(tcp_c_dir)

.cpp : $(tcp_c_dir)

.asm.obj :
  wasm -0 $(memory_model) $[*

.cpp.obj :
  wpp $[* $(compile_options)

hello.obj : hello.asm
  nasm -f obj hello.asm -o hello.obj

bot.com: $(tcpobjs) $(objs)
  wlink debug all system com option map, eliminate, symfile, quiet name $@ file *.obj
